variables:
  CI_REGISTRY_IMAGE: personal-area-app:latest
  CI_REGISTRY_BACKEND_IMAGE: personal-area-node-app:latest
  REGISTRY_SERVER_ADDRESS: "192.168.79.14:5000"
  PROD_SERVER_IP: "192.168.79.113"
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/  
stages:
  - build
  - docker-build
  - deploy

build:
  stage: build
  image: node:20
  script: 
    - echo "Start building App"
    - npm install
    - npm run build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/


#docker-build-backend:
#  stage: docker-build
#  image: docker:latest
#  services: 
#    - name: docker:19.03.8-dind
  #before_script:
  #  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#  script:    
#    - docker build --pull -t "$CI_REGISTRY_BACKEND_IMAGE" ./server
#    - docker push "$REGISTRY_SERVER_ADDRESS/$CI_REGISTRY_BACKEND_IMAGE"
#    - echo "Registry backend image:" $CI_REGISTRY_BACKEND_IMAGE

docker-build-frontend:  
  image: docker:latest
  stage: docker-build
  before_script:
    - docker info
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $REGISTRY_SERVER_ADDRESS -u $CI_REGISTRY_USER --password-stdin
    - docker build --pull -t "$REGISTRY_SERVER_ADDRESS/$CI_REGISTRY_IMAGE" .
    - docker push ${REGISTRY_SERVER_ADDRESS}/${CI_REGISTRY_IMAGE}

deploy-dev:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY yashin@$PROD_SERVER_IP "docker pull $REGISTRY_SERVER_ADDRESS/$CI_REGISTRY_IMAGE"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY yashin@$PROD_SERVER_IP "docker stop personal-area-next-app || true && docker rm personal-area-next-app || true"
    - ssh -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY yashin@$PROD_SERVER_IP "docker run -p 3000:3000 -d --name personal-area-next-app $REGISTRY_SERVER_ADDRESS/$CI_REGISTRY_IMAGE"   


