version: "3"

services:
  next-app:
    depends_on:
      - nodejs
    container_name: next-app
    env_file: .env
    build:    
      context: .
      dockerfile: Dockerfile
      # args:
      #  ENV_VARIABLE: ${ENV_VARIABLE}
      #  NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - 3000:3000      
  nodejs:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    # environment:
    ports:
      - "4000:4000"
    volumes:
      - ./server:/home/node/app
      - ./server/node_modules:/home/node/app/node_modules

