version: "3"

services:
  nodejs:
    build:
      context: .
      #dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    # environment:
    ports:
      - "4000:4000"
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules

